### ISSUE TITLE
External configuration of server url

### ISSUE THREAD

**Issue by gpdoud** [gpdoud/ams-client#2]
At the moment, the server URL is hard-coded in all the Angular services (asset, location, user, vehicle) files. There must be a way to change the server URL **without changing program code**. One possibility is a file that is read in by the system service which then can provide the URL to all the other services.

This change of the URL must be available at installation time where the code cannot be changed. It probably must be stored in some external file

**Comment by mbaugus** [comment]
In the /environments folder there is a production and non-production file to declare global constants like that ( i think anyways )  It would be a good idea to define it there I think.

change this 
```
export const environment = {  
  production: false
};
```

to 
```
export const environment = {  
  production: false,
  serverURL: 'http://localhost:61612/' or whatrever
};
```
then use like this
```
import { environment } from './environment';
this.url = environment.serverURL;
```
Does this satisfy the requirement?

**Comment by gpdoud** [comment]
It does not. I added some more to the issue because the change of the URL called by the services must be done at installation time when no code changes are possible. This probably means putting the URL in some external text file (e.g. JSON) that can be read in at application initialization time.

**Comment by mbaugus** [comment]
I added a new pull request/branch that should meet the requirement.
